# shellcheck shell=bash

format:
   #!/usr/bin/env bash
   fourmolu -i src app test
   fourmolu -i src app test
   fourmolu -i src app test
   cabal-fmt -i adversary.cabal
   # shellcheck disable=SC2035
   nixfmt *.nix
   nixfmt nix/*.nix

hlint:
  #!/usr/bin/env bash
  hlint app src test

build:
    #!/usr/bin/env bash
    cabal build all --enable-tests --enable-benchmarks

test:
  #!/usr/bin/env bash
  cabal test --enable-tests --enable-benchmarks

local-testnet:
  #!/usr/bin/env bash
  cd ../compose/testnets/cardano_node_with_adversary
  INTERNAL_NETWORK=false docker compose up

antithesis-build:
  #!/usr/bin/env bash
  nix build .#docker-image
  version=$(nix eval --raw .#version)
  docker load < ./result
  docker tag \
    "ghcr.io/cardano-foundation/cardano-node-antithesis/adversary:$version" \
    ghcr.io/cardano-foundation/cardano-node-antithesis/adversary:dev

CI:
  #!/usr/bin/env bash
  just format
  just hlint
  just build
  just test
