#!/bin/sh
# provision-control-channel.sh — stand up the DWARF web-driven substrate
# control channel on a deploy host. Idempotent; safe to re-run.
#
# What it does (all local to the deploy host):
#   1. Generate a dedicated ed25519 keypair (once).
#   2. Install the forced-command shim + its config.
#   3. Append a RESTRICTED forced-command entry to authorized_keys so the key
#      can ONLY invoke the shim (no shell, no tunneling, no pty).
#   4. Pin this host's SSH host key into a known_hosts file.
#   5. Stage the private key + known_hosts where the dashboard container's
#      compose bind-mounts expect them.
#
# Portability: POSIX sh + standard OpenSSH (ssh-keygen, ssh-keyscan). No
# systemd, no distro-specific packages. Runs on Linux / macOS / WSL2.
#
# Override any of these via environment before running:
#   DEPLOY_USER   (default: current user)
#   DEPLOY_HOST   (default: 127.0.0.1)
#   INSTALL_DIR   (default: $HOME/dwarf-control)
#   DWARF_ROOT    (default: autodetected <repo>/dwarf)
#   REMOTE_BASE_PATH (default: $HOME/cardano-profiles)
#   STATE_DIR     (default: <repo>/var/state — where the container mount reads)
#   TOPOLOGY_PACKAGE_DIR (default: the shipped mixed-control Compose package)
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)

DEPLOY_USER=${DEPLOY_USER:-$(id -un)}
DEPLOY_HOST=${DEPLOY_HOST:-127.0.0.1}
INSTALL_DIR=${INSTALL_DIR:-$HOME/dwarf-control}
DWARF_ROOT=${DWARF_ROOT:-$REPO_ROOT/dwarf}
# Single runtime-root base — deploy writes here and remove archives from here.
REMOTE_BASE_PATH=${REMOTE_BASE_PATH:-/opt/dwarf/cardano-profiles}
STATE_DIR=${STATE_DIR:-$REPO_ROOT/var/state}
RUNTIME_ROOT=$(dirname "$STATE_DIR")
RUNS_DIR=${RUNS_DIR:-$RUNTIME_ROOT/runs}
BUNDLES_DIR=${BUNDLES_DIR:-$RUNTIME_ROOT/bundles}
# Writable profile overlay the dashboard container creates profiles into, so the
# host-side generator sees GUI-created profiles (not just the baked catalog).
PROFILES_DIR=${PROFILES_DIR:-$STATE_DIR/profiles}
# Scenario overlay (same bind-mount the container uses) + AFL coverage harness,
# so the `coverage` verb can run aflpp scenarios on the host where AFL works.
SCENARIOS_DIR=${SCENARIOS_DIR:-$STATE_DIR/scenarios}
LAUNCH_ROOT=${LAUNCH_ROOT:-$STATE_DIR/launches}
CONFIG_PATH=${CONFIG_PATH:-$STATE_DIR/config.yaml}
AFL_HARNESS=${AFL_HARNESS:-/opt/dwarf/afl-harness/dwarf-decode-any}
AFL_FUZZ=${AFL_FUZZ:-/opt/dwarf/afl-harness/afl-fuzz}
TOPOLOGY_PACKAGE_DIR=${TOPOLOGY_PACKAGE_DIR:-$REPO_ROOT/antithesis/cardano_amaru_relay_bootstrap_control}

KEY_COMMENT="dwarf-control-channel"
SHIM_INSTALL="$INSTALL_DIR/dwarf-deploy-shim"
CONF_INSTALL="$INSTALL_DIR/dwarf-control.conf"
AUDIT_LOG="$INSTALL_DIR/dwarf-control.log"
KEY_PATH="$INSTALL_DIR/dwarf-deploy-key"
AUTH_KEYS="$HOME/.ssh/authorized_keys"

echo "==> DWARF control-channel provisioning"
echo "    deploy target : $DEPLOY_USER@$DEPLOY_HOST"
echo "    install dir   : $INSTALL_DIR"
echo "    DWARF_ROOT    : $DWARF_ROOT"
echo "    remote base   : $REMOTE_BASE_PATH"
echo "    state dir     : $STATE_DIR"

if [ ! -d "$DWARF_ROOT/profile_manager" ]; then
  echo "!! DWARF_ROOT does not look like a DWARF checkout (no profile_manager/): $DWARF_ROOT" >&2
  exit 1
fi

# Ensure the runtime-root base exists and is writable by the deploy user.
if ! mkdir -p "$REMOTE_BASE_PATH" 2>/dev/null; then
  echo "==> $REMOTE_BASE_PATH needs elevated creation; using sudo"
  sudo mkdir -p "$REMOTE_BASE_PATH"
  sudo chown -R "$DEPLOY_USER" "$REMOTE_BASE_PATH"
fi

mkdir -p "$INSTALL_DIR"
chmod 700 "$INSTALL_DIR"
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"
mkdir -p "$STATE_DIR"
mkdir -p "$LAUNCH_ROOT"
chmod 700 "$LAUNCH_ROOT"

# 1. Keypair (generate once; never overwrite an existing one).
if [ ! -f "$KEY_PATH" ]; then
  echo "==> generating ed25519 keypair"
  ssh-keygen -t ed25519 -N "" -C "$KEY_COMMENT" -f "$KEY_PATH" >/dev/null
else
  echo "==> keypair already present (reusing)"
fi
chmod 600 "$KEY_PATH"
PUBKEY=$(cat "$KEY_PATH.pub")

# 2. Install shim + config.
echo "==> installing shim + config"
cp "$SCRIPT_DIR/dwarf-deploy-shim.py" "$SHIM_INSTALL"
chmod 755 "$SHIM_INSTALL"
cat > "$CONF_INSTALL" <<EOF
# generated by provision-control-channel.sh — safe to edit paths
DWARF_ROOT=$DWARF_ROOT
REMOTE_BASE_PATH=$REMOTE_BASE_PATH
PROFILES_DIR=$PROFILES_DIR
SCENARIOS_DIR=$SCENARIOS_DIR
LAUNCH_ROOT=$LAUNCH_ROOT
STATE_DIR=$STATE_DIR
RUNS_DIR=$RUNS_DIR
BUNDLES_DIR=$BUNDLES_DIR
CONFIG_PATH=$CONFIG_PATH
AFL_HARNESS=$AFL_HARNESS
AFL_FUZZ=$AFL_FUZZ
TOPOLOGY_PACKAGE_DIR=$TOPOLOGY_PACKAGE_DIR
AUDIT_LOG=$AUDIT_LOG
EOF
chmod 600 "$CONF_INSTALL"

# 3. Restricted forced-command authorized_keys entry (idempotent).
OPTS="restrict,command=\"$SHIM_INSTALL\""
ENTRY="$OPTS $PUBKEY"
touch "$AUTH_KEYS"
chmod 600 "$AUTH_KEYS"
# Drop any prior entry for this key comment, then append the fresh one.
if grep -q "$KEY_COMMENT" "$AUTH_KEYS" 2>/dev/null; then
  grep -v "$KEY_COMMENT" "$AUTH_KEYS" > "$AUTH_KEYS.tmp" || true
  mv "$AUTH_KEYS.tmp" "$AUTH_KEYS"
  chmod 600 "$AUTH_KEYS"
fi
printf '%s\n' "$ENTRY" >> "$AUTH_KEYS"
echo "==> authorized_keys entry installed (restrict + forced-command)"

# 4. Pin host key into a known_hosts file.
echo "==> pinning host key for $DEPLOY_HOST"
KNOWN_HOSTS="$STATE_DIR/ssh_known_hosts"
: > "$KNOWN_HOSTS.tmp"
ssh-keyscan -H "$DEPLOY_HOST" >> "$KNOWN_HOSTS.tmp" 2>/dev/null || true
if [ -s "$KNOWN_HOSTS.tmp" ]; then
  mv "$KNOWN_HOSTS.tmp" "$KNOWN_HOSTS"
  chmod 644 "$KNOWN_HOSTS"
else
  rm -f "$KNOWN_HOSTS.tmp"
  echo "!! ssh-keyscan returned nothing for $DEPLOY_HOST — is sshd reachable there?" >&2
fi

# 5. Stage the private key + known_hosts for the container bind-mounts.
echo "==> staging private key for container mount"
cp "$KEY_PATH" "$STATE_DIR/ssh_deploy_key"
chmod 600 "$STATE_DIR/ssh_deploy_key"

echo ""
echo "==> DONE. Verify the channel with:"
echo "    ssh -i \"$KEY_PATH\" -o UserKnownHostsFile=\"$KNOWN_HOSTS\" $DEPLOY_USER@$DEPLOY_HOST active"
echo "    (expect: active-devnet listing or empty; NOT a shell)"
echo "    ssh -i \"$KEY_PATH\" $DEPLOY_USER@$DEPLOY_HOST 'rm -rf /'   # must be REFUSED"
echo ""
echo "Then set the dashboard container config:"
echo "    ssh_key_path = /home/dwarf/.ssh/dwarf-deploy"
echo "    host         = $DEPLOY_HOST"
echo "    ssh_user     = $DEPLOY_USER"
echo "    and set ADA2_DWARF_CONTROL_SHIM=1 in the compose env."
